# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kakaotalk_Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~>5.2'

  # Pods for Kakaotalk_Clone

  target 'Kakaotalk_CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kakaotalk_CloneUITests' do
    # Pods for testing
  end

end
